// Login types

export const LOGIN_FORM_INPUT_CHANGE = 'LOGIN_FORM_INPUT_CHANGE';
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING';
export const LOGIN_FORM_ERROR = 'LOGIN_FORM_ERROR';
export const LOGIN_FORM_SUCCESS = 'LOGIN_FORM_SUCCESS';